### ISSUE TITLE
has_secure_password

### ISSUE THREAD

**Issue by randallreedjr** [learn-co-curriculum/sinatra-fwitter-group-project#11]
Test suite should include a check that the User model utilizes `has_secure_password`. Project should not be submitted until this is implemented.

cc @aviflombaum

**Comment by AnnJohn** [comment]
@vicfriedman can you look at this?

**Comment by vicfriedman** [comment]
Hey @AnnJohn and @randallreedjr made a PR for this issue a couple of weeks ago: https://github.com/learn-co-curriculum/sinatra-fwitter-group-project/pull/13
