### ISSUE TITLE
Check for helper methods

### ISSUE THREAD

**Issue by randallreedjr** [learn-co-curriculum/sinatra-fwitter-group-project#12]
May be helpful to add tests for presence of `current_user` and `logged_in?` helper methods. This would help guide students in their development and avoid reimplementing this logic.

cc @aviflombaum

**Comment by vicfriedman** [comment]
it seems like Sinatra requires some special setup to be able to test helpers - http://netzfisch.github.io/ruby/2014/02/14/testing-sinatra-helpers-with-rspec.html & https://github.com/padrino/padrino-framework/issues/930.

Both of these involve updating how we teach creating helpers to be able to access them in the tests in earlier parts of the curriculum

**Comment by vicfriedman** [comment]
thoughts @pletcher

**Comment by pletcher** [comment]
Hm, I think this is good to keep track of -- and part of me is in favor of de-emphasizing the Sinatra-specific helper approach in favor of the more generic module approach -- but we might have to come back to this one.

Thanks for opening this issue, @randallreedjr. I'm going to close it for now, but I've made a note to come back to this problem when we get a chance.
