### ISSUE TITLE
Uninitialized Constant User from tests when there is a user model

### ISSUE THREAD

**Issue by genericlady** [learn-co-curriculum/sinatra-fwitter-group-project#17]
the .rspec file in the root of the project needs the flag `--require spec_helper` otherwise you have to explicitly declare `require 'spec_helper' at top of the specs and you will get a fail since you're not loading in the environment.

```
# .rspec
--color
--format documentation
--require spec_helper
```

**Comment by tyleresmith** [comment]
Confirming this issue still exists.

**Comment by AnnJohn** [comment]
for web 0416
