### ISSUE TITLE
"problem updating team" error

### ISSUE THREAD

**Issue by dkennell** [learn-co-curriculum/sinatra-fwitter-group-project#22]
When I try to set my group option to "working solo", I get an error message in the form of a red bar across the top of the page that reads "There was a problem updating your team. Please reload and try again." If I refresh the page, I once again have no group selected. I can't check any of the other boxes or do anything else in the way of submitting my assignment, so I'm kind of stuck here. 

Thanks for your time,
David Kennell

**Comment by Lukeghenco** [comment]
Hi @dkennell thank you for raising this issue. I believe this has been resolved now. Please let me know if this is still an issue.
