### ISSUE TITLE
Instructions are misleading

### ISSUE THREAD

**Issue by cdudhat** [learn-co-curriculum/sinatra-fwitter-group-project#25]
Last Paragraph "**Protecting the Views**" says - 

> You'll need to make sure that no one can create, read, edit or delete any tweets.

While, the test -

`delete action > logged in > does not let a user delete a tweet they did not create`

requires that any "logged in" user, who is not necessarily the "owner" of the tweet can also view the show page. Ideally, why would a user who does not "own" the tweet be able to see the detailed "show_tweet" page of the tweet that does not belong to him? Instead of making a non-working "Delete" and "Edit" buttons for a non belonging tweet.

**Comment by Lukeghenco** [comment]
Thanks @cdudhat this has been updated & fixed. Thank you for raising the issue.
