### ISSUE TITLE
Known Issues

### ISSUE THREAD

**Issue by curiositypaths** [learn-co-curriculum/sinatra-fwitter-group-project#37]
PROBLEM: Improve specs. See issue #36.
NOTIFY: @nenlightened

**Comment by curiositypaths** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#37.  We will add this to our internal work queue and notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team

**Comment by drakeltheryuujin** [comment]
PROBLEM: As of June 18 2018 one test still does not work #48
NOTIFY: @justinddaniel

PROBLEM: Fwitter read-me / spec content confusion #41
NOTIFY: @raiet13

PROBLEM: awaiting new solution for wip-enforce-etc.-branch, needs completion asap #42
NOTIFY: @DanielSeehausen

**Comment by drakeltheryuujin** [comment]
Status:
#36 resolved
