### ISSUE TITLE
Fwitter read-me / spec content confusion

### ISSUE THREAD

**Issue by raiet13** [learn-co-curriculum/sinatra-fwitter-group-project#41]
Hello! 

This is definitely my first time contributing and I apologize if anything I have laid out is unclear. I did not try to make either of the changes myself as the situation itself has me perplexed and I'm not sure what the correlation exactly is between the "error" that started it all and the "solution" which resolved the error. The below is separated into 3 parts, the original situation and the 2 points of confusion that somehow led to the error's resolution.

I hope that this helps!

----------

Original Issue : Getting "http://example.com" as random redirect in "get '/logout'" route code. Tech coach checked their comparison code and it looked "exactly the same".

Solution? : Reorganize code AND update code based on error despite spec content.

Note : Adding the below content notes as they appeared to be the source of this issue and fix, though I'm still not entirely sure how the combination of the two managed to fix this super weird error that I still don't understand the cause of.

----------

Read-Me Situation : The read-me "File Structure" only includes the "application_controller.rb" which, given that not all of the other files/folders in the structure were in the base fork and the lack of additional controller specs, implied that all coding was to be done in that one file. 

Read-Me Issue : Tech coach had me separate my code to use two additional controllers "users_controller.rb" and "tweets_controller.rb".

Read-Me Notes : While this was a fine segmentation and one that I would utilize in personal projects, I've gotten used to following the read-me/base in order to "ensure that tests pass". Therefore, I didn't know that I was "supposed" to be doing the segmentation and that it was expected of me.

----------

Spec Situation : In the logout portion of the "application_controller_spec.rb" spec, it was confusing about exactly what the redirects were supposed to be for the "user logged in" and "user not logged in" situations.

Spec Issue : In the "lets a user logout if they are already logged in" and "does load /tweets if user is logged in" tests, the "expect(last_response.location).to include("/login")" is "login". However, in the test that exists between them, the "does not let a user logout if not logged in" test, the expected location is "expect(last_response.location).to include("/")".

Spec Notes : By having the logout route always redirect to the "login" route, I was able to get all three tests to pass. The verbiage of the tests though was very confusing, especially since I was getting a result of "http://example.com" that didn't make sense as it doesn't exist anywhere in the code that I could find.

**Comment by DanielSeehausen** [comment]
Thank you @raiet13 ! This is incredible work and we certainly appreciate it -- a model perfect issue. We will work on addressing these comments asap!

**Comment by drakeltheryuujin** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#37. We will add this to our internal work queue and
notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team
