### ISSUE TITLE
As of June 18 2018 one test still does not work

### ISSUE THREAD

**Issue by justinddaniel** [learn-co-curriculum/sinatra-fwitter-group-project#48]
Test:   it 'does not let user view login page if already logged in' do
      user = User.create(:username => "becky567", :email => "starz@aol.com", :password => "kittens")

      params = {
        :username => "becky567",
        :password => "kittens"
      }
      post '/login', params
      session = {}
      session[:user_id] = user.id
      get '/login'
      expect(last_response.location).to include("/tweets")
    end
  end

Student code clearly behaves properly in browser: location '/tweets'
test returns nil for location. 
It appears new users are still not being persisted and logged in by the test.

**Comment by drakeltheryuujin** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#37.  We will add this to our internal work queue and
notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team
