### ISSUE TITLE
Fwitter URL update needed

### ISSUE THREAD

**Issue by onyoo** [learn-co-curriculum/sinatra-fwitter-group-project#5]
When I finished reading the README on learn.co, I ran 'learn open' but I got an odd error:

```
// ♥ learn open
Getting current lesson...
Something went wrong. Please try again.
[09:55:46] ~
// ♥ learn open
Getting current lesson...
Something went wrong. Please try again.
```
I tried clicking on the 'View in GitHub' link but was greeted with a cool 404. I searched for it, but couldn't find it. Perhaps I was on the learn-co-students page. I gave-up.

A few hours later, I was looking through my Github repositories and saw that the Fwitter lab had magically appeared. I went back to the lab on learn.co, but it was still marked as not-forked:
<img width="1140" alt="screen shot 2015-12-27 at 1 44 20 pm" src="https://cloud.githubusercontent.com/assets/14326883/12010278/ff2382f4-ac9f-11e5-84c6-aca992adb879.png">
<img width="1091" alt="screen shot 2015-12-27 at 1 45 13 pm" src="https://cloud.githubusercontent.com/assets/14326883/12010280/1a1239d4-aca0-11e5-8d75-6b9ec6b51570.png">

The only thing I know for sure is that the 'View on GitHub' link needs updating:

current:    URL: https://github.com/learn-co-students/sinatra-fwitter-group-project-v-000
correct:    URL: https://github.com/learn-co-curriculum/sinatra-fwitter-group-project

**Comment by AnnJohn** [comment]
thanks for raising this issue @onyoo. We'll look into it Monday morning!

**Comment by onyoo** [comment]
I finished the lab and pushed to GitHub using 'learn submit'. 

```
[10:31:57] (master) sinatra-fwitter-group-project
// ♥ learn submit
Adding changes...
Committing changes...
Pushing changes to GitHub...
Submitting lesson...
Hmm...this doesn't appear to be a Learn lesson. Are you in the right directory?
```

Something's still up with the pull request. I manually submitted a PR, so you will see that there is one, if you look.

As one would guess, the lab page on learn.co is still unresponsive:

<img width="1165" alt="screen shot 2015-12-28 at 10 43 09 am" src="https://cloud.githubusercontent.com/assets/14326883/12016805/d344cdb8-ad4f-11e5-9700-1dab1d571fa6.png">

**Comment by danielchangNYC** [comment]
Hi @onyoo , sorry you're having trouble with this lab. Can you tell me how you forked the lab? (e.g. did you click the Open button on the browser?)

**Comment by onyoo** [comment]
Hey, @danielchangNYC, I ran ```learn open``` and got the message shown above. I went to find the lab but couldn't find it from learn-co-students, so I gave-up looking. To be honest, I don't know how this copy showed-up in my repos.

**Comment by danielchangNYC** [comment]
Got it, thanks. Also, in what dir did you run `learn open`?

**Comment by onyoo** [comment]
@danielchangNYC  My Terminal.

**Comment by danielchangNYC** [comment]
Where did you get the https://github.com/learn-co-curriculum/sinatra-fwitter-group-project link from? Or are you also not sure how that was cloned to your machine?

**Comment by onyoo** [comment]
I got it from the clone that somehow got to my GitHub repo. If it wasn't cloned from using 'learn open', then I must have done something by accident. I don't know how it got there. Once I found it in my repo, thinking that it was the correct version (since the README was the same) I manually cloned it to my machine.

**Comment by AnnJohn** [comment]
Hi @onyoo this should be working correctly now.  Could you take a look at let us know? Thanks!

**Comment by onyoo** [comment]
Hi @AnnJohn, thanks for letting me know! I see the 'View on GitHub' link is working now.

I can ask another student if he was able to use the 'learn open' command. I submitted a PR this morning with no problems, and am in the process of submitting the next lab. I don't know how to use 'learn' to fork a previous lesson. However, 'learn open sinatra-fwitter-group-project' does open the correct lesson in chrome.

I hope this info helps!

**Comment by AnnJohn** [comment]
Hi @onyoo great, glad that it's working. I'm not sure if learn can fork a previous lesson, but we did fix the issue with this lesson and just wanted to make sure it was working correctly for you. Thanks for raising the issue!
