### ISSUE TITLE
Three empty spec folders

### ISSUE THREAD

**Issue by ValerieHMoore** [learn-co-curriculum/sinatra-fwitter-group-project#51]
In the spec folder under controllers, there are three empty files:
- application_controller.rb
- tweets_controller.rb
- users_controller.rb

All of the tests are in application_controller_spec.rb, so I believe you can delete the three empty folders.

Thank you.

**Comment by cjbrock** [comment]
Hi @ValerieHMoore! 

I'm having difficulty reproducing the issue, so I'm going to close it for now. Is the spec folder under the controllers the correct folder? If you could give me a link to the appropriate files on github,  I'd be happy to take a second look!

As always, thanks for contributing!
// <3 Corinna

**Comment by ValerieHMoore** [comment]
Hi Corinna, happy to help! Sorry, I meant three empty files, not folders.
In the /spec/controllers folder, all of the tests are in one file, and the
other three files are empty. The empty files are:
application_controller.rb, tweets.controller.rb, and users.controller.rb.
All of the tests are in application_controller_spec.rb. My suggested
solution would be to rename the "real" tests file with a more general name,
such as fwitter_spec.rb, and then delete the empty files.

Here is a link to my GitHub if you need it:
https://github.com/ValerieHMoore/sinatra-fwitter-group-project-v-000/tree/master/spec/controllers.
If you need further clarification, I am happy to screen share or whatever
else you need.

Thanks,

Valerie
