### ISSUE TITLE
tweets/new.erb instead of tweets/create_tweet.erb

### ISSUE THREAD

**Issue by ValerieHMoore** [learn-co-curriculum/sinatra-fwitter-group-project#52]
The file tree shown in the readme under views/tweets shows a create_tweet.erb, so I created one as directed. However, the tests in application_controller_spec.rb are looking for "visit '/tweets/new'," not "visit '/tweets/create_tweet'." I created new.erb and deleted create_tweet.erb; other students reported the same to me.

My suggested solution would be to rename the file in the readme to match what's required in the tests.

Thank you.

**Comment by drakeltheryuujin** [comment]
We've updated the README.md.

Thanks 💙
