### ISSUE TITLE
KNOWN ISSUES: Test error

### ISSUE THREAD

**Issue by atxrenegade** [learn-co-curriculum/sinatra-fwitter-group-project#53]
Test not persisting data causing test to fail. Confirmed by Justin Daniels.
Application_controller_spec line 140

  describe 'user show page' do
    xit 'shows all a single users tweets' do
      user = User.create(:username => "becky567", :email => "starz@aol.com", :password => "kittens")
	  #binding.pry
     ****** tweet1 = Tweet.create(:content => "tweeting!", :user_id => user.id)******
      tweet2 = Tweet.create(:content => "tweet tweet tweet", :user_id => user.id)
      get "/users/#{user.slug}"

     ****** expect(last_response.body).to include("tweeting!")*****
      expect(last_response.body).to include("tweet tweet tweet")

    end
  end

**Comment by drakeltheryuujin** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#37. We will add this to our internal work queue and
notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team
