### ISSUE TITLE
 flash error upon pressing the submit

### ISSUE THREAD

**Issue by kev112** [learn-co-curriculum/sinatra-fwitter-group-project#54]
Ran all tests and pull request, but getting this flash error upon pressing the submit button in learnco:

POST https://api.github.com/repositories/73721277/pulls: 422 - Validation Failed Error summary: resource: PullRequest field: head code: invalid // See: https://developer.github.com/v3/pulls/#create-a-pull-request

**Comment by drakeltheryuujin** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#37. We will add this to our internal work queue and
notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team
