### ISSUE TITLE
could not find expected ':' while scanning a simple key at line 10 column 1

### ISSUE THREAD

**Issue by ivalentine** [learn-co-curriculum/sinatra-fwitter-group-project#55]
When running `learn` on this lab, the following error message appears:

```
/usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/psych.rb:377:in &#96;parse': (<unknown>): could not find expected ':' while scanning a simple key at line 10 column 1 (Psych:
:SyntaxError)
        from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/psych.rb:377:in &#96;parse_stream'
        from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/psych.rb:325:in &#96;parse'
        from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/psych.rb:252:in &#96;load'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/learn-test-2.6.1/lib/learn_test/strategies/green_onion.rb:53:in &#96;yaml'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/learn-test-2.6.1/lib/learn_test/strategies/green_onion.rb:49:in &#96;green_onion_lab?'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/learn-test-2.6.1/lib/learn_test/strategies/green_onion.rb:16:in &#96;detect'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/learn-test-2.6.1/lib/learn_test/runner.rb:35:in &#96;each'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/learn-test-2.6.1/lib/learn_test/runner.rb:35:in &#96;detect'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/learn-test-2.6.1/lib/learn_test/runner.rb:35:in &#96;strategy'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/learn-test-2.6.1/lib/learn_test/runner.rb:10:in &#96;initialize'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/learn-test-2.6.1/bin/learn-test:68:in &#96;new'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/learn-test-2.6.1/bin/learn-test:68:in &#96;<top (required)>'
        from /usr/local/rvm/gems/ruby-2.3.1/bin/learn-test:23:in &#96;load'
        from /usr/local/rvm/gems/ruby-2.3.1/bin/learn-test:23:in &#96;<main>'
```

We have tried:
* Quitting and re-opening the IDE
* Deleting the lab directory and re-cloning

There appears to be a merge conflict in the `.learn` file which is preventing Psych from parsing it correctly. Deleting the lab directory and re-cloning did not change this.

*Environment info:*
Learn IDE v3.0.0
Windows 10

Reported by @assetrecon.

**Comment by sgharms** [comment]
Hi there! This request sounds like an improvement to or a problem with the Learn platform.

Our product team can help you with this. You can reach them at support@learn.co.

[Raising issues on GitHub][raise], like you've done here should happen when
there are problems with the curriculum itself (doesn't work, throws a Ruby
error, etc.)

If, on the other hand, we've misunderstood the purpose of this request, please
re-open this issue, provide any additional information you can to clarify our error,
and we will try to find a fix.

[raise]: http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson
