### ISSUE TITLE
this section is so unorganized

### ISSUE THREAD

**Issue by paurosero** [learn-co-curriculum/sinatra-fwitter-group-project#59]
learning this whole sinatra labs were so hard because its so out of order and so difficult to learn what im trying to do. I am just guessing what im supposed to do because i feel the previous labs/notes were not in order for a student to grasp how to build a webpage. i feel they just put things down as they remembered. this lab has so many misspellings too.

**Comment by drakeltheryuujin** [comment]
Hi @paurosero,

Thank you for your feedback! We'll take this information into consideration in upcoming releases of this curriculum.

As always, thanks for contributing! 💙
