### ISSUE TITLE
Not able to choose Solo or Team, or check items in Complete Checklist until page refresh

### ISSUE THREAD

**Issue by levimllr** [learn-co-curriculum/sinatra-fwitter-group-project#61]
Hey! Not sure if I don't understand how or whether this interface is supposed to work in the teacher-onboarding track, but I couldn't select Solo or Team under Choose Team or check items under Complete Checklist until I refreshed the page. My experience was as follows:
1. Fork lab, get first green circle. Not able to choose team.
2. Refresh page.
3. Able to choose team. Chose solo. Got second green circle. Not able to check items under checklist.
4. Refresh page again.
5. Able to check items under Complete Checklist.

**Comment by sgharms** [comment]
Hi there! This request sounds like an improvement to or a problem with the Learn platform.

Our product team can help you with this. You can reach them at support@learn.co.

Or, since it sounds like you're internal, you can use the JIRA board and add an issue to the LABSBOARD project.
