### ISSUE TITLE
This lab is very confused

### ISSUE THREAD

**Issue by ChristopherBlack22** [learn-co-curriculum/sinatra-fwitter-group-project#79]
This lab doesn't make use of RESTful routes yet advices the student to. The tests for logging out do not work if you try to use the logout view that has been provided, even if in reality it works properly, meaning you have to fudge it as in the solution.

**Comment by ihollander** [comment]
Hi @ChristopherBlack22 - thanks for your feedback! I've made some updates to the starter code based on your comments in #80, including removing the non-working `logout.erb` file. With regards to RESTful routing, the routes for the Tweet model follow RESTful conventions, but the routes for the User model do not. Many applications follow a similar pattern of designing routes that break RESTful convention to handle authorization, so it's useful to get practice with these kind of routes as well.
